// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_n9Zgj9XeQVyN7M7Pek9KsqK31Cnt6cs',
    appId: '1:527431373240:web:7e8253817b2d6a2e083f4d',
    messagingSenderId: '527431373240',
    projectId: 'flutter-expert-submission2',
    authDomain: 'flutter-expert-submission2.firebaseapp.com',
    storageBucket: 'flutter-expert-submission2.appspot.com',
    measurementId: 'G-3B70S638XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx8pV8GlfZ4QLDzueXgb0BjIgVbc83Go',
    appId: '1:527431373240:android:8e2f8eeab0484bdd083f4d',
    messagingSenderId: '527431373240',
    projectId: 'flutter-expert-submission2',
    storageBucket: 'flutter-expert-submission2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASpibmkeSX-fO-bedFWWLckSnJkC8AeBk',
    appId: '1:527431373240:ios:bacccc7e49be565c083f4d',
    messagingSenderId: '527431373240',
    projectId: 'flutter-expert-submission2',
    storageBucket: 'flutter-expert-submission2.appspot.com',
    iosClientId: '527431373240-a4vv4i0mr699ppava5gv66jm9mkhklor.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
