// Mocks generated by Mockito 5.0.8 from annotations
// in ditonton/test/presentation/pages/movie_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/tvseries/tvseries.dart' as _i10;
import 'package:ditonton/domain/entities/tvseries/tvseries_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/tvseries/get_detail_tvseries.dart' as _i2;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_recommendation.dart' as _i3;
import 'package:ditonton/domain/usecases/tvseries/get_watchlist_status_tv.dart' as _i4;
import 'package:ditonton/domain/usecases/tvseries/remove_watchlist_tv.dart' as _i6;
import 'package:ditonton/domain/usecases/tvseries/save_watchlist_tv.dart' as _i5;
import 'package:ditonton/presentation/provider/tvseries/tv_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetTvSeriesDetail extends _i1.Fake implements _i2.GetTvSeriesDetail {}

class _FakeGetTvSeriesRecommendations extends _i1.Fake
    implements _i3.GetTvSeriesRecommendations {}

class _FakeGetTvSeriesWatchlistStatus extends _i1.Fake
    implements _i4.GetWatchlistStatusTvSeries {}

class _FakeGetTvSeriesWatchlistSave extends _i1.Fake implements _i5.SaveWatchlistTvSeries {}

class _FakeGetTvSeriesWatchlistRemove extends _i1.Fake implements _i6.RemoveWatchlistTvSeries {}

class _FakeTvSeriesDetail extends _i1.Fake implements _i7.TvSeriesDetail {}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i8.TvDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesDetail),
          returnValue: _FakeGetTvSeriesDetail()) as _i2.GetTvSeriesDetail);
  @override
  _i3.GetTvSeriesRecommendations get getTvRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTvRecommendations),
              returnValue: _FakeGetTvSeriesRecommendations())
          as _i3.GetTvSeriesRecommendations);
  @override
  _i4.GetWatchlistStatusTvSeries get getWatchlistStatusTv =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistStatusTv),
          returnValue: _FakeGetTvSeriesWatchlistStatus()) as _i4.GetWatchlistStatusTvSeries);
  @override
  _i5.SaveWatchlistTvSeries get saveWatchlistTv =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlistTv),
          returnValue: _FakeGetTvSeriesWatchlistSave()) as _i5.SaveWatchlistTvSeries);
  @override
  _i6.RemoveWatchlistTvSeries get removeWatchlistTv =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlistTv),
          returnValue: _FakeGetTvSeriesWatchlistRemove()) as _i6.RemoveWatchlistTvSeries);
  @override
  _i7.TvSeriesDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tvSeries),
      returnValue: _FakeTvSeriesDetail()) as _i7.TvSeriesDetail);
  @override
  _i9.RequestState get tvDetailState =>
      (super.noSuchMethod(Invocation.getter(#tvDetailState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.TvSeries> get tvRecommendation =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendation),
          returnValue: <_i10.TvSeries>[]) as List<_i10.TvSeries>);
  @override
  _i9.RequestState get tvRecommendationState =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchListTv =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchListTv),
          returnValue: false) as bool);
  @override
  String get watchlistMessageTv =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessageTv), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTvSeriesDetail, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvSeries]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlistTv(_i7.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlistTv, [tvSeries]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatusTv(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatusTvSeries, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
